# AEA Agent Configuration
# This file defines how this agent processes inter-agent messages

agent:
  id: "claude-$(basename $(pwd))"
  name: "Claude Code Agent"
  description: "Autonomous development agent for $(basename $(pwd))"
  capabilities:
    - code_analysis
    - documentation
    - testing
    - debugging
    - performance_optimization

# Message Processing Policies
response_policy:
  # Questions: Auto-respond with technical answers
  question:
    auto_respond: true
    approval_required: false
    actions:
      - search_codebase
      - analyze_code
      - provide_answer
      - send_response

  # Updates: Acknowledge or summarize based on priority
  update:
    normal:
      auto_respond: true
      approval_required: false
      actions:
        - read_update
        - acknowledge_if_requested
    high:
      auto_respond: true
      approval_required: false
      actions:
        - read_update
        - summarize_for_user
    urgent:
      auto_respond: true
      approval_required: false
      actions:
        - read_update
        - notify_user
        - summarize_key_points

  # Issues: Auto-analyze low/medium, request approval for high/urgent
  issue:
    low:
      auto_respond: true
      approval_required: false
      actions:
        - analyze_issue
        - suggest_fix
        - send_response
    medium:
      auto_respond: true
      approval_required: false
      actions:
        - analyze_issue
        - suggest_fix
        - send_response
    high:
      auto_respond: false
      approval_required: true
      actions:
        - analyze_issue
        - notify_user
        - wait_for_approval
    urgent:
      auto_respond: false
      approval_required: true
      actions:
        - analyze_issue
        - notify_user
        - wait_for_approval

  # Handoffs: Always review with user
  handoff:
    auto_respond: false
    approval_required: true
    actions:
      - summarize_handoff
      - notify_user
      - wait_for_approval

  # Requests: Evaluate and respond with plan
  request:
    auto_respond: true
    approval_required: false
    actions:
      - analyze_request
      - create_plan
      - send_response

# Auto-safe operations (no approval needed)
auto_safe_operations:
  - read_files
  - search_codebase
  - analyze_code
  - generate_documentation
  - answer_questions
  - create_response_messages
  - log_actions

# Operations requiring approval
approval_required_operations:
  - modify_code
  - change_configuration
  - deploy_changes
  - delete_files
  - security_changes
  - database_operations

# Monitoring
monitoring:
  enabled: true
  log_file: ".aea/agent.log"
  check_interval: 60  # seconds
