#!/bin/bash
#
# Dune Analytics + OSVM - Practical Use Cases
# This script demonstrates useful blockchain analytics combining Dune's historical data
# with OSVM's real-time RPC capabilities
#

OSVM="./target/debug/osvm a"

echo "=================================================="
echo "  Dune Analytics + OSVM: Practical Demo"
echo "=================================================="
echo ""

# Use Case 1: Historical + Real-time Comparison
echo "📊 Use Case 1: Compare Historical vs Current Wallet Activity"
echo "------------------------------------------------------------"
echo ""
echo "Query: Analyze a whale wallet's current holdings vs historical patterns"
echo ""
WHALE="5rVDMMoBQs3zJQ9DT7oxsoNZfxptgLCKhuWqdwoX9q85"

echo "Step 1: Get current real-time balance..."
$OSVM "get SOL balance for $WHALE" | head -20
echo ""

echo "Step 2: Cross-reference with Dune historical data..."
echo "→ Would query Dune for historical balance changes, trading patterns, etc."
echo "→ This requires creating a custom query on dune.com first"
echo ""

# Use Case 2: Token Analytics
echo ""
echo "📈 Use Case 2: Deep Token Analysis"
echo "------------------------------------------------------------"
echo ""
TOKEN="pvv4fu1RvQBkKXozyH5A843sp1mt6gTy9rPoZrBBAGS"

echo "Combining multiple data sources for: $TOKEN"
echo ""
echo "✓ Real-time: Current transactions, holder count (OSVM RPC)"
echo "✓ Historical: Price history, volume trends (Dune)"
echo "✓ Analysis: Pattern detection, anomaly flagging (AI)"
echo ""

# Use Case 3: DEX Aggregation
echo ""
echo "💱 Use Case 3: Multi-DEX Arbitrage Detection"
echo "------------------------------------------------------------"
echo ""
echo "Dune Query: Historical arbitrage opportunities across Orca, Raydium, Jupiter"
echo "OSVM Query: Current live prices and liquidity"
echo "Output: Real-time arbitrage alerts with historical success rates"
echo ""
echo "Example query:"
echo "  $OSVM \"compare SOL/USDC prices across Orca and Raydium, show arbitrage spread\""
echo ""

# Use Case 4: NFT Analytics
echo ""
echo "🖼️  Use Case 4: NFT Collection Intelligence"
echo "------------------------------------------------------------"
echo ""
echo "Dune: Floor price history, holder distribution, wash trading detection"
echo "OSVM: Current listings, recent sales, live floor price"
echo "Combined: Buy/sell signals based on historical patterns + current market"
echo ""

# Use Case 5: Wallet Profiling
echo ""
echo "🔍 Use Case 5: Smart Money Tracking"
echo "------------------------------------------------------------"
echo ""
echo "Track profitable wallets (from Dune historical analysis)"
echo "Monitor their current trades in real-time (OSVM)"
echo "Get alerts when they make moves (automated OVSM scripts)"
echo ""
echo "Example:"
echo "  1. Identify top 100 profitable traders from Dune"
echo "  2. Monitor their wallets with OSVM"
echo "  3. Copy their strategies automatically"
echo ""

# Use Case 6: Protocol Analytics
echo ""
echo "⚙️  Use Case 6: DeFi Protocol Deep Dive"
echo "------------------------------------------------------------"
echo ""
echo "For any Solana protocol:"
echo "  • Historical TVL, volume, fees (Dune)"
echo "  • Current state, active positions (OSVM)"
echo "  • Risk assessment, health metrics (AI Analysis)"
echo "  • Comparative analysis vs competitors"
echo ""

echo ""
echo "=================================================="
echo "  Getting Started"
echo "=================================================="
echo ""
echo "1. Create Custom Dune Queries:"
echo "   → Visit dune.com"
echo "   → Write SQL queries for your specific analytics needs"
echo "   → Note the query IDs"
echo ""
echo "2. Use with OSVM:"
echo "   $OSVM \"execute Dune query [YOUR_ID]\""
echo ""
echo "3. Combine Data Sources:"
echo "   • Dune: Historical patterns, aggregations"
echo "   • OSVM: Real-time state, current prices"
echo "   • AI: Pattern recognition, predictions"
echo ""
echo "4. Automate with OVSM Scripts:"
echo "   • Schedule queries"
echo "   • Set up alerts"
echo "   • Build dashboards"
echo ""
echo "=================================================="
echo "  Example Dune Queries to Create"
echo "=================================================="
echo ""
echo "Query Type          | What It Shows"
echo "--------------------|---------------------------------"
echo "Whale Movements     | Top 100 wallets by transfer volume"
echo "DEX Volume Trends   | Daily volume by DEX over 30 days"
echo "Token Holder Growth | New holders per day"
echo "Smart Money         | Wallets with >80% profitable trades"
echo "Arbitrage History   | Past arb opportunities and profits"
echo "Gas Optimization    | Cost savings from batch transactions"
echo ""
echo "=================================================="
echo ""
echo "📚 Full Documentation:"
echo "   docs/integrations/dune-analytics-mcp-setup.md"
echo ""
echo "🔧 Your Setup:"
echo "   API Key: Configured ✓"
echo "   MCP Server: Installed ✓"
echo "   Tools: execute_dune_query, get_query_results, get_token_balances ✓"
echo ""
echo "🚀 Ready to use! Start by creating queries on dune.com"
echo "=================================================="
