#set document(title: "OSVM Security Audit Report")
#set page(numbering: "1")
#set text(size: 11pt)
#set heading(numbering: "1.")

#align(center)[
  #text(size: 24pt, weight: "bold")[OSVM Security Audit Report]
  
  #v(1em)
  
  #text(size: 14pt)[Comprehensive Security Assessment]
  
  #v(2em)
  
  #text(size: 12pt)[
    Generated: {{ timestamp }}
    
    Version: {{ version }}
    
    Security Score: {{ summary.security_score }}/100
    
    Compliance Level: {{ summary.compliance_level }}
  ]
]

#pagebreak()

= Executive Summary

This report presents the results of a comprehensive security audit conducted on the OSVM (Open SVM) CLI application. The audit identified {{ summary.total_findings }} findings across various security domains.

#table(
  columns: (auto, auto),
  stroke: none,
  [*Metric*], [*Value*],
  [Total Findings], [{{ summary.total_findings }}],
  [Critical], [{{ summary.critical_findings }}],
  [High], [{{ summary.high_findings }}],
  [Medium], [{{ summary.medium_findings }}],
  [Low], [{{ summary.low_findings }}],
  [Info], [{{ summary.info_findings }}],
  [Security Score], [{{ summary.security_score }}/100],
  [Compliance Level], [{{ summary.compliance_level }}],
)

{% if has_critical or has_high %}
#text(fill: red, weight: "bold")[
  ⚠️ This audit identified {{ total_serious }} critical or high severity findings that require immediate attention.
]
{% endif %}

= System Information

#table(
  columns: (auto, auto),
  stroke: none,
  [*Component*], [*Version*],
  [Rust], [{{ system_info.rust_version }}],
  [Solana], [{{ system_info.solana_version | default(value="Not installed") }}],
  [OS], [{{ system_info.os_info }}],
  [Architecture], [{{ system_info.architecture }}],
)

= Security Findings

{% for category, findings in categorized_findings %}
== {{ category }} ({{ findings | length }} findings)

{% for finding in findings %}
=== {{ finding.id }} - {{ finding.title }}

*Severity:* {{ finding.severity }}
*Category:* {{ finding.category }}
{% if finding.cwe_id %}*CWE ID:* {{ finding.cwe_id }}{% endif %}
{% if finding.cvss_score %}*CVSS Score:* {{ finding.cvss_score }}{% endif %}

*Description:*
{{ finding.description }}

*Impact:*
{{ finding.impact }}

*Recommendation:*
{{ finding.recommendation }}

{% if finding.code_location %}*Code Location:* {{ finding.code_location }}{% endif %}

{% if finding.references %}
*References:*
{% for reference in finding.references %}
- {{ reference }}
{% endfor %}
{% endif %}

{% endfor %}
{% endfor %}

= Security Recommendations

{% for recommendation in recommendations %}
{{ loop.index }}. {{ recommendation }}

{% endfor %}

= Compliance Notes

{% for note in compliance_notes %}
- {{ note }}
{% endfor %}

= Statistics

#table(
  columns: (auto, auto),
  stroke: none,
  [*Metric*], [*Value*],
  [Total Findings], [{{ statistics.total_findings }}],
  [Findings with CWE], [{{ statistics.findings_with_cwe }}],
  [Findings with CVSS], [{{ statistics.findings_with_cvss }}],
  [Findings with Location], [{{ statistics.findings_with_location }}],
  [Unique Categories], [{{ statistics.unique_categories }}],
  [Average CVSS Score], [{{ "%.1f" | format(statistics.average_cvss_score) }}],
  [Coverage Percentage], [{{ "%.1f" | format(statistics.coverage_percentage) }}%],
)

= Conclusion

This security audit provides a comprehensive assessment of the OSVM CLI application's security posture. All identified findings should be addressed according to their severity level, with critical and high-severity issues taking priority.

{% if has_critical %}
#text(fill: red, weight: "bold")[
  ⚠️ CRITICAL: {{ summary.critical_findings }} critical findings require immediate remediation.
]
{% endif %}

{% if has_high %}
#text(fill: orange, weight: "bold")[
  ⚠️ HIGH: {{ summary.high_findings }} high-severity findings should be addressed promptly.
]
{% endif %}

Regular security assessments and continuous monitoring are recommended to maintain a strong security stance.

#align(center)[
  #text(size: 10pt, style: "italic")[
    Generated by OSVM Security Audit System
    
    End of Report
  ]
]