name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
        working-directory: .
      
      - name: Run cargo-audit
        run: cargo audit
        working-directory: .
      
      - name: Run cargo-deny
        run: cargo deny check advisories
        working-directory: .

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

  code-scanning:
    name: Code Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: rust
        env:
          CODEQL_ENABLE_EXPERIMENTAL_FEATURES: true
      
      - name: Build
        run: cargo build
        working-directory: .
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
